### ISSUE TITLE
Estimación de tiempos - Desgloce WBS

### ISSUE THREAD

**Issue by mrebasti** [mrebasti/utn-frba-proyecto-2015#30]

**Comment by mrebasti** [comment]
Muevo el issue de milestone por que no lo llegamos a terminar para la entrega del martes pasado.

**Comment by gnicolao** [comment]
Yo lo daria por cerrado ya que habia mandado un wbs, y para la semana 9 ya tenemos uno nuevo mejorado. Si no estan de acuerdo por favor vuelvan a abrirlo.

**Comment by nataliapalau** [comment]
Si.. me parece que está cerrado...

ES decir.. ya lo mandamos.

2015-06-15 20:23 GMT-03:00 gnicolao <notifications@github.com>:

> Yo lo daria por cerrado ya que habia mandado un wbs, y para la semana 9 ya
> tenemos uno nuevo mejorado. Si no estan de acuerdo por favor vuelvan a
> abrirlo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrebasti/utn-frba-proyecto-2015/issues/30#issuecomment-112236365>
> .
>



-- 
Besos!
Naty

**Comment by mrebasti** [comment]
Falta agregarlo al documento de gestión

2015-06-15 20:39 GMT-03:00 nataliapalau <notifications@github.com>:

**Comment by nataliapalau** [comment]
yo lo dejaría como anexo

2015-06-15 22:29 GMT-03:00 Marcelo Rebasti <notifications@github.com>:

> Falta agregarlo al documento de gestión
>
> 2015-06-15 20:39 GMT-03:00 nataliapalau <notifications@github.com>:
>
> > Si.. me parece que está cerrado...
> >
> > ES decir.. ya lo mandamos.
> >
> >
> > 2015-06-15 20:23 GMT-03:00 gnicolao <notifications@github.com>:
> >
> > > Yo lo daria por cerrado ya que habia mandado un wbs, y para la semana 9
> > ya
> > > tenemos uno nuevo mejorado. Si no estan de acuerdo por favor vuelvan a
> > > abrirlo.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/mrebasti/utn-frba-proyecto-2015/issues/30#issuecomment-112236365
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Besos!
> > Naty
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mrebasti/utn-frba-proyecto-2015/issues/30#issuecomment-112238320
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrebasti/utn-frba-proyecto-2015/issues/30#issuecomment-112253595>
> .
>



-- 
Besos!
Naty
