### ISSUE TITLE
Plan de riesgos

### ISSUE THREAD

**Issue by mrebasti** [mrebasti/utn-frba-proyecto-2015#40]

**Comment by nataliapalau** [comment]
sorry.. por qué está reopened!?!?

Yo hice las correcciones que pidió!

On Mon, Jun 22, 2015 at 1:17 PM, munozgonzaloa <notifications@github.com>
wrote:

> Reopened #40
> <https://github.com/mrebasti/utn-frba-proyecto-2015/issues/40>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrebasti/utn-frba-proyecto-2015/issues/40#event-336885320>
> .
>



-- 
Besos!
Naty

**Comment by nataliapalau** [comment]
Si es para hacer correcciones, no re abramos issues, generemos uno nuevo.

On Mon, Jun 22, 2015 at 6:21 PM, Natalia Palau <natalia.palau@gmail.com>
wrote:

> sorry.. por qué está reopened!?!?
>
> Yo hice las correcciones que pidió!
>
> On Mon, Jun 22, 2015 at 1:17 PM, munozgonzaloa <notifications@github.com>
> wrote:
>
>> Reopened #40
>> <https://github.com/mrebasti/utn-frba-proyecto-2015/issues/40>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mrebasti/utn-frba-proyecto-2015/issues/40#event-336885320>
>> .
>>
>
>
>
> --
> Besos!
> Naty
>



-- 
Besos!
Naty

**Comment by munozgonzaloa** [comment]
Dale, lo cierro.
