### ISSUE TITLE
Creación de prototipos de pantallas

### ISSUE THREAD

**Issue by mrebasti** [mrebasti/utn-frba-proyecto-2015#69]
Crear prototipos de pantallas que nos van a servir para el documento de desarrollo de producto, pero también para terminar de redondear entre nosotros varios aspectos funcionales y de usabilidad de las aplicaciones.

**Comment by nataliapalau** [comment]
Yo lo hago esto.




2015-06-16 0:31 GMT-03:00 Marcelo Rebasti <notifications@github.com>:

> Crear prototipos de pantallas que nos van a servir para el documento de
> desarrollo de producto, pero también para terminar de redondear entre
> nosotros varios aspectos funcionales y de usabilidad de las aplicaciones.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrebasti/utn-frba-proyecto-2015/issues/69>.
>



-- 
Besos!
Naty

**Comment by mrebasti** [comment]
prefiero hacer los primeros yo sobre html, y a lo sumo después vos trabajas
sobre eso

2015-06-16 9:48 GMT-03:00 nataliapalau <notifications@github.com>:

**Comment by nataliapalau** [comment]
Oka.. dale

2015-06-16 10:12 GMT-03:00 Marcelo Rebasti <notifications@github.com>:

> prefiero hacer los primeros yo sobre html, y a lo sumo después vos trabajas
> sobre eso
>
> 2015-06-16 9:48 GMT-03:00 nataliapalau <notifications@github.com>:
>
> > Yo lo hago esto.
> >
> >
> >
> >
> > 2015-06-16 0:31 GMT-03:00 Marcelo Rebasti <notifications@github.com>:
> >
> > > Crear prototipos de pantallas que nos van a servir para el documento de
> > > desarrollo de producto, pero también para terminar de redondear entre
> > > nosotros varios aspectos funcionales y de usabilidad de las
> aplicaciones.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/mrebasti/utn-frba-proyecto-2015/issues/69>.
> > >
> >
> >
> >
> > --
> > Besos!
> > Naty
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mrebasti/utn-frba-proyecto-2015/issues/69#issuecomment-112414420
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrebasti/utn-frba-proyecto-2015/issues/69#issuecomment-112423614>
> .
>



-- 
Besos!
Naty

**Comment by mrebasti** [comment]
Agregué las capturas del prototipo a la versión 1.3 del documento de desarrollo de producto.
